CREATE TABLE book (
                        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        fio varchar(100) NOT NULL,
                        name varchar(100) NOT NULL,
                        ageOfEdition int not null CHECK(ageOfEdition > 1500 and ageOfEdition < 2022),
                        style varchar(100) NOT NULL,
                        countOfPage int not null CHECK(countOfPage > 0)
);

INSERT INTO book (fio, name, ageOfEdition, style, countOfPage)
VALUES
    ('Пушкин Ф.Щ.', 'Сад', 1900, 'худ', 200),
    ('Толстой Ф.Щ.', 'Жук', 1980, 'худ', 100),
    ('Чехов Ф.Щ.', 'Гад', 2000, 'худ', 2000),
    ('Лермонтов Ф.Щ.', 'Сало', 1800, 'худ', 500),
    ('Блок Ф.Щ.', 'Кот',2020, 'худ', 4900);